dendritic-api:
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  environment:
    RETHINKDB_URL: rethinkdb://rethinkdb:28015/dendritic_api
    PORT: 3005
  ports:
    - 3005:3005
  links:
    - rethinkdb

rethinkdb:
  image: rethinkdb:latest
